In [23]:
import numpy as np
random_int_array = np.random.randint(1, 50, size=10)
random_int_array

array([ 1, 12, 16, 27,  3, 32,  3, 21, 34, 48], dtype=int32)

In [21]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.2 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:
import numpy as np
random_int_array = np.random.randint(1, 50, size=10)
random_int_array

array([17, 39, 31, 21, 39, 21, 41,  7, 21,  5], dtype=int32)

In [19]:
random_int_array = np.random.randint(10, 100, size=(2, 5))
random_int_array

array([[21, 18, 62, 80, 76],
       [28, 97, 22, 43, 84]], dtype=int32)

In [24]:
random_int_array = np.random.randint(1, 50, size=10)
np.mean(random_int_array)

np.float64(24.3)

In [ ]:
a = np.random.randint(10, 100, size=(3, 3))
b = np.random.randint(10, 100, size=(3, 3))
ab=a+b
np.mean(random_int_array)